---
services:
  db:
    image: jyothikac/libraryrepo:dbimage
    ports:
     - "3306:3306"
    deploy:
      replicas: 1
  auth_service:
    image: jyothikac/libraryrepo:authimage
    ports:
      - "5001:5001"
    deploy:
      replicas: 3
  book_service:
    image: jyothikac/libraryrepo:bookimage
    ports:   
      - "5002:5002"
    deploy:
      replicas: 3
  borrow_service:
    image: jyothikac/libraryrepo:borrowimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 3
  frontend:
    image: jyothikac/libraryrepo:appimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
